# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Github Action for LaTeX
      uses: xu-cheng/latex-action@1.2.1
      with:
    # The root LaTeX file to be compiled
        root_file: divyanshi-sharma.tex

    - name: upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: pdf
        path: divyanshi-sharma.pdf

    - name: upload artifact to gh-pages
      run: |
        # configure git
        git config --global user.name "Divyanshi Sharma"
        git config --global user.email "divyanss@usc.edu"
        # setup ssh
        mkdir ~/.ssh
        chmod 700 ~/.ssh
        echo "$DEPLOY_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        git config --global core.sshCommand "ssh -i ~/.ssh/id_ed25519 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
        git clone --depth=1 --branch gh-pages git@github.com:divyanshi26/resume.git "$GITHUB_WORKSPACE/deploy"
        cp -f divyanshi-sharma.pdf "$GITHUB_WORKSPACE/deploy/divyanshi-sharma.pdf"
        cd "$GITHUB_WORKSPACE/deploy"
        git add divyanshi-sharma.pdf
        git commit -m "[github actions] deploy"
        git push
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
